Portfolio: RWD - Desktop Version using Media Queries
peterdtitan/portfolio-build pull request #4
Opened 2022-06-04 01:42 UTC by peterdtitan

Updated the portfolio build to using responsive web design processed. The following files were changed: 

- index.html (Used semantic tags)
- styles.css (added media queries)
- assets (added more assets to aid visual design)

<img width="1440" alt="Screenshot 2022-06-04 at 4 34 31 AM" src="https://user-images.githubusercontent.com/70844072/171971698-21f3374d-4bf8-4ce2-a1bd-d18ca92fcb64.png">

<img width="1440" alt="Screenshot 2022-06-04 at 4 35 01 AM" src="https://user-images.githubusercontent.com/70844072/171971677-c060837f-9b3c-48f1-b5b7-9ae85e78ba28.png">
4161-acf4-045c3213c44c.png">

<img width="1440" alt="Screenshot 2022-06-04 at 4 35 15 AM" src="https://user-images.githubusercontent.com/70844072/171971691-44721cdb-654f-4896-836a-c9382f8bd11f.png">

2022-06-04 02:45 UTC, Kandy-Peter requested changes
Hi @ManarOmari 

Good job so far! I know you have worked hard on making this milestone. There is an issue that you still need to work on to go to the next project but you are almost there!

![almost-there-almost](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] I would advise you to implement your cards the way that the featured project is followed by 2 rows with 3 projects each (6 projects in total).
- [x] It would be nice if after the project description there were some buttons like tags listing all the technologies that were used to build the project as designed in the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)
- [x] Please, ensure that when the project is hovered on with the mouse the description and dark opacity disappears and a `See Project` button appears to the bottom of the image and takes the whole image width mentioned button should take you to the Live Demo of the project or to the GitHub repository.
**1. Check your design**
![image](https://user-images.githubusercontent.com/80612925/171975283-1f1ebecd-4d9e-421e-a1ed-3505efaeaee5.png)
**2. Figma design**
![image](https://user-images.githubusercontent.com/80612925/171975342-52745c08-15ed-404b-a887-07626bcca04a.png)

- [x] REQUESTED: 
     -I would suggest you add more black colours to your social icons to stick the Figma design.
        ![image](https://user-images.githubusercontent.com/80612925/171975534-a2ab963b-a93c-4398-ae17-e7a366580518.png)

**1. Figma design**

![image](https://user-images.githubusercontent.com/80612925/171975630-6e95c1e4-3530-4636-a684-372387fa3b44.png)

 
- [x] Kindly check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 02:45 UTC, Kandy-Peter commented on index.html
> +            <hr>
- [ ] Please, ensure that The Title `"My Recent Works"`  is aligned to the left and after there's a line that takes the rest of the page's width.
**1.You design**
![image](https://user-images.githubusercontent.com/80612925/171974732-db4d76f0-658c-4e7c-872d-8b58e2ad61c8.png)
2. Figma **design**
![image](https://user-images.githubusercontent.com/80612925/171974767-de8366d3-71df-4c57-9e42-fb55c41b1fa9.png)

2022-06-04 13:49 UTC, peterdtitan commented
Made design changes to match the given template: 
-  Updated the responsiveness of headers and other elements
- Made changes to image resizing and use grid layout to add more cards. 

<img width="1440" alt="Screenshot 2022-06-04 at 4 45 12 PM" src="https://user-images.githubusercontent.com/70844072/172003592-6f4ba793-b75d-4463-b9e9-e31bf35f63f2.png">

<img width="1440" alt="Screenshot 2022-06-04 at 4 45 25 PM" src="https://user-images.githubusercontent.com/70844072/172003606-915d9f32-591d-4e2c-bdfc-c6230a11a262.png">

2022-06-04 13:54 UTC, algerina approved these changes
Hi @peterdtitan , 
Good job so far! :fire: 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed, however use a descriptive feature branch:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 

<img src="https://media1.giphy.com/media/bdaMVCP6bPIVWc0B3g/giphy.gif"/>
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-04 13:57 UTC, merged

2022-10-11 06:54 UTC, ManarOmari commented
Hello , the project is :   Portfolio: mobile version
<https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md>
not for desktop and the code you have sent in images to update it not for
me

On Sat, Jun 4, 2022 at 5:45 AM Kandy Peter Kamuntu ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @ManarOmari <https://github.com/ManarOmari>
>
> Good job so far! I know you have worked hard on making this milestone.
> There is an issue that you still need to work on to go to the next project
> but you are almost there!
>
> [image: almost-there-almost]
> <https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - You are following GitHub actions ✔️
>    - Good commit history ✔️
>    - Good PR description ✔️
>
> Required Changes ♻️
>
>    -
>
>    I would advise you to implement your cards the way that the featured
>    project is followed by 2 rows with 3 projects each (6 projects in total).
>    -
>
>    It would be nice if after the project description there were some
>    buttons like tags listing all the technologies that were used to build the
>    project as designed in the Figma template
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471>
>    -
>
>    Please, ensure that when the project is hovered on with the mouse the
>    description and dark opacity disappears and a See Project button
>    appears to the bottom of the image and takes the whole image width
>    mentioned button should take you to the Live Demo of the project or to the
>    GitHub repository.
>    *1. Check your design*
>    [image: image]
>    <https://user-images.githubusercontent.com/80612925/171975283-1f1ebecd-4d9e-421e-a1ed-3505efaeaee5.png>
>    *2. Figma design*
>    [image: image]
>    <https://user-images.githubusercontent.com/80612925/171975342-52745c08-15ed-404b-a887-07626bcca04a.png>
>    -
>
>    REQUESTED:
>    -I would suggest you add more black colours to your social icons to
>    stick the Figma design.
>    [image: image]
>    <https://user-images.githubusercontent.com/80612925/171975534-a2ab963b-a93c-4398-ae17-e7a366580518.png>
>
> *1. Figma design*
>
> [image: image]
> <https://user-images.githubusercontent.com/80612925/171975630-6e95c1e4-3530-4636-a684-372387fa3b44.png>
>
>    - Kindly check the comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/peterdtitan/portfolio-build/pull/4#discussion_r889441979>
> :
>
> > @@ -71,6 +73,7 @@ <h2 class="container job-title">I am a Software Developer</h2>
>
>      <section class="works-header">
>
>          <div class="works-title">
>
>              <h1>My Recent Works</h1>
>
> +            <hr>
>
>
>
>    - Please, ensure that The Title "My Recent Works" is aligned to the
>    left and after there's a line that takes the rest of the page's width.
>    *1.You design*
>    [image: image]
>    <https://user-images.githubusercontent.com/80612925/171974732-db4d76f0-658c-4e7c-872d-8b58e2ad61c8.png>
>
>
>    1. Figma *design*
>    [image: image]
>    <https://user-images.githubusercontent.com/80612925/171974767-de8366d3-71df-4c57-9e42-fb55c41b1fa9.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/peterdtitan/portfolio-build/pull/4#pullrequestreview-995666442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDTEI2TFHXR6EP6GOIWXMDVNK7OLANCNFSM5X2T7MAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>